name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-node:
    name: Node.js Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node: ${{ matrix.node }}
    - run: npm install
    - run: npm run build
    - run: npm run test
  